version: '3.1'

services:
  notes-backend:
    build: .
    restart: always
    container_name: test-sb
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo-database

  mongo-database:
    image: mongo
    container_name: test-m
    volumes:
      - ~/docker-mongo-data:/data/db
    restart: always